---
kind: pipeline
type: docker
name: pipeline
steps:
- name: build and publish (${DRONE_BRANCH})
  image: plugins/docker
  settings:
    repo:
      from_secret: docker_repository
    tags: latest
    dockerfile: Dockerfile
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    event:
      - push
    branch:
      - master


- name: build and publish (${DRONE_TAG})
  image: plugins/docker
  settings:
    repo:
      from_secret: docker_repository
    tags: ${DRONE_TAG}
    dockerfile: Dockerfile
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    event:
      - tag
